### ISSUE TITLE
Behavior of "other" in "Which configuration systems"

### ISSUE THREAD

**Issue by markus2330** [sirblackheart/elektrasurvey#81]
When I click at any item, I well get two lines for the smiley (should be one)

Then, when I click at other, it says "Other:" in the second line (should be other: or (change text above))

**Comment by sirblackheart** [comment]
Nice catch. This should be fixed now. Please test if there are any similar errors.

**Comment by omnidan** [comment]
When I select `other:`, it still shows `Other` (capitalized) for the smiley question:

![https://i.imgur.com/ZpAeYhk.png](https://i.imgur.com/ZpAeYhk.png)

The other issue seems to be fixed now.

**Comment by omnidan** [comment]
I changed it to `other`.

**Comment by sirblackheart** [comment]
good catch, thanks for fixing it. it also should change to the text you type into the previous field once you type something there.

**Comment by omnidan** [comment]
@sirblackheart I'm not sure what you mean. It changes `other` to the text I entered once I start typing in the field above.

**Comment by sirblackheart** [comment]
Yes exactly that.

**Comment by omnidan** [comment]
@sirblackheart Is it not working for you? I just tested it and it seems to work fine here.

**Comment by sirblackheart** [comment]
@omnidan no i just wanted to note that it works that way so you could could test if it works correctly. everythings fine, thank you

**Comment by omnidan** [comment]
Ah, ok. Thanks for letting me know!

**Comment by markus2330** [comment]
Thank you, looks fine now!
